### ISSUE TITLE
Multiple clocks

### ISSUE THREAD

**Issue by djungelola** [smarthomejunkie/Ulanzi-Awtrix-BluePrints#2]
Hi
I have two clocks, what is the easiest and smartest way to handle them?
Do i have to have multiple automations per clock and multiple helpers?

Br Ola

**Comment by smarthomejunkie** [comment]
Please visit my Discord server for questions.

[Discord Server](https://discord.gg/WqCF4MEAt8)
[Ulanzi Channel](https://discord.com/channels/743727205246566483/1090978984835170414)
