### ISSUE TITLE
Rain Forecast not working with 0.87/0.88 Awtrix Light and Home Assistant 2023.9.2

### ISSUE THREAD

**Issue by ragman11** [smarthomejunkie/Ulanzi-Awtrix-BluePrints#7]
Hi,

Thank you for your great work with the Blueprints. Since I refreshed the Blueprints (1.76) and updated it in HA, the RainForecast Toogle will not activate anymore. With a lower Version of your Blueprints it will work.

br
Mike

**Comment by smarthomejunkie** [comment]
Hi Mike,
I'm not sure what you mean, but there's no Version 1.76 of my Blueprints.
The latest version is 1.75. Also, make sure that your HA version is at
least 2023.9 otherwise this blueprint will not work.

Kind regards,
Ed

**Comment by ragman11** [comment]
Hi Ed, sorry for the confusion, it was 1.74. I will try 1.75.

br
Mike

**Comment by smarthomejunkie** [comment]
Ok, no problem.
