### ISSUE TITLE
it's a shame

### ISSUE THREAD

**Issue by e-p-s** [smarthomejunkie/Ulanzi-Awtrix-BluePrints#8]
I truly appreciate the hard work and dedication you've put into creating these Blueprints. However, I believe that selling them is not the best approach. You are using free and open-source software like Home Assistant and the AWTRIX project to create content for your channel. These projects are built on the principle of sharing knowledge and resources freely within the community. By monetizing the Blueprints, it seems like you're taking advantage of the open-source ethos without contributing back.

Many people in the community, including the developers of these projects, spend countless hours contributing their skills and expertise for free, making it possible for enthusiasts like us to create and innovate. Selling Blueprints could discourage others from sharing their work openly, which would ultimately harm the collaborative spirit that drives open-source projects.

It would be more in line with the values of the open-source community to offer these Blueprints for free. This way, you not only honor the work of those who developed the software you rely on, but also encourage a culture of sharing and mutual support. Additionally, you could consider other ways to monetize your efforts, such as through donations, sponsorships, or exclusive content for supporters, which would be a fairer way to benefit from your hard work without compromising the community-driven nature of these projects.

**Comment by smarthomejunkie** [comment]
Read my statement about this here: [https://www.smarthomejunkie.net/shop/#whydoiaskformoney](url)
